services:
  qwen3_embedding_4b_worker_template:
    extends:
      file: ../../../model.base.yml
      service: base_worker_template
    build:
      context: ../../../..
      dockerfile: images/vllm_worker/Dockerfile
