apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # 'prometheus' is the DNS hostname of the container in the 'onion' network
    url: http://prometheus:9090 
    isDefault: true
    editable: false
