services:
  test_mock_stt_worker_template:
    extends:
      file: ../../../model.base.yml
      service: base_worker_template
    build:
      context: ../../../..
      dockerfile: images/dummy_vllm_worker/Dockerfile
